name: Changelog Update
on:
  schedule:
    - cron: "0 * * * * "
jobs:
  run:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v1
    - uses: ./.github/actions/changelog-pull-action
      id: changelog_pull
      env:
        FAUNADB_TOKEN: ${{ secrets.FAUNADB_TOKEN }}
    - name: Build if new posts
      if: steps.changelog_pull.outputs.newFaunaPostsAdded != "0"
      env:
        NETLIFY_SITE_ID: ${{ secrets.NETLIFY_SITE_ID }}
        NETLIFY_AUTH_TOKEN: ${{ secrets.NETLIFY_AUTH_TOKEN }}
      run: |
        yarn
        yarn build
        npx netlify-cli deploy --dir=public --prod
